version: '3.7'

services:

  chat-app:
    container_name: chat-app
    build:
      context: chat-web-app
      dockerfile: Dockerfile
    volumes:
      - '.:/chat-web-app/app'
      - '/chat-web-app/app/node_modules'
    stdin_open: true
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true